version: '3.7'
services:
  deployment-hub:
    container_name: deployment-hub
    build: https://github.com/jaredwines/deployment-hub.git
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ~/.ssh:/root/.ssh

# To run Deployment-Hub from docker use the following command.
# $ docker-compose --env-file /home/deployment-hub/deployment-hub.env --file /home/deployment-hub/docker-compose.yml up -d --build
