version: '3.7'
services:
  deployment-hub:
    container_name: deployment-hub
    build: https://github.com/jaredwines/deployment-hub.git#${BRANCH}
    restart: unless-stopped
    ports:
      - "5555:5555"
    volumes:
      - /home/deploymenthub/.ssh:/root/.ssh
      - /home/deploymenthub/Projects/deployment-hub/configuration.json:/usr/src/deployment-hub/configuration.json
    env_file:
      - /home/deploymenthub/Projects/deployment-hub/.env

# To run Deployment-Hub from docker use the following command with env file.
# $ docker-compose --env-file /home/deployment-hub/.env --file /home/deployment-hub/docker-compose.yml up -d --build

# To run Deployment-Hub from docker use the following command without env file.
# $ docker-compose --file /home/deployment-hub/docker-compose.yml up -d --build
