version: '3.7'
services:
  deployment-hub:
    container_name: deployment-hub
    build: https://github.com/jaredwines/deployment-hub.git#${BRANCH}
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ~/.ssh:/root/.ssh
    env_file:
      - /home/jared/Projects/deployment-hub/.env

# To run Deployment-Hub from docker use the following command with env file.
# $ docker-compose --env-file /home/deployment-hub/deployment-hub.env --file /home/deployment-hub/docker-compose.yml up -d --build

# To run Deployment-Hub from docker use the following command without env file.
# $ docker-compose --file /home/deployment-hub/docker-compose.yml up -d --build
