pushversion: '3.7'

services:
  deployment-hub:
    container_name: deployment-hub
    image: jaredwines/deployment-hub
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ~/.ssh:/root/.ssh